<?php 
 return [ 'components' =>['db' =>['class'=>'yii\db\Connection',
'dsn'=>'mysql:host=localhost; port=3306;dbname=volatil',
'username'=>'root',
'password'=>'',
'charset'=>'utf8',
'tablePrefix'=>'sgxle_',
],
'mailer' =>['class'=>'common\components\Mailer',
'viewPath'=>'@common/mail',
true],
'settings' =>['class'=>'yii2mod\settings\components\Settings',
],
],
];  ?>